package com.eqms.model;
// default package
// Generated 2015-11-14 00:29:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pictures generated by hbm2java
 */
@Entity
@Table(name = "pictures", catalog = "exam_questions_5", uniqueConstraints = @UniqueConstraint(columnNames = "PICTURE_NAME") )
public class Picture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pictureId;
	private String pictureName;
	private String pictureType;
	private byte[] picture;
	private Set<Answer> answerses = new HashSet<Answer>(0);
	private Set<Question> questionses = new HashSet<Question>(0);

	public Picture() {
	}

	public Picture(String pictureName, String pictureType, byte[] picture) {
		this.pictureName = pictureName;
		this.pictureType = pictureType;
		this.picture = picture;
	}

	public Picture(String pictureName, String pictureType, byte[] picture, Set<Answer> answerses,
			Set<Question> questionses) {
		this.pictureName = pictureName;
		this.pictureType = pictureType;
		this.picture = picture;
		this.answerses = answerses;
		this.questionses = questionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PICTURE_ID", unique = true, nullable = false)
	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	@Column(name = "PICTURE_NAME", unique = true, nullable = false, length = 30)
	public String getPictureName() {
		return this.pictureName;
	}

	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	@Column(name = "PICTURE_TYPE", nullable = false, length = 4)
	public String getPictureType() {
		return this.pictureType;
	}

	public void setPictureType(String pictureType) {
		this.pictureType = pictureType;
	}

	@Column(name = "PICTURE", nullable = false)
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pictures")
	public Set<Answer> getAnswerses() {
		return this.answerses;
	}

	public void setAnswerses(Set<Answer> answerses) {
		this.answerses = answerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pictures")
	public Set<Question> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Question> questionses) {
		this.questionses = questionses;
	}

}
