package com.eqms.model;
//default package
//Generated 2015-11-14 00:29:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SetsOfRating generated by hbm2java
 */
@Entity
@Table(name = "sets_of_rating", catalog = "exam_questions_5")
public class SetOfRating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer setId;
	private int mark5;
	private int mark4_5;
	private int mark4;
	private int mark3_5;
	private int mark3;
	private int mark2;
	private Set<Test> testses = new HashSet<Test>(0);

	public SetOfRating() {
	}

	public SetOfRating(int mark5, int mark4_5, int mark4, int mark3_5, int mark3, int mark2) {
		this.mark5 = mark5;
		this.mark4_5 = mark4_5;
		this.mark4 = mark4;
		this.mark3_5 = mark3_5;
		this.mark3 = mark3;
		this.mark2 = mark2;
	}

	public SetOfRating(int mark5, int mark4_5, int mark4, int mark3_5, int mark3, int mark2, Set<Test> testses) {
		this.mark5 = mark5;
		this.mark4_5 = mark4_5;
		this.mark4 = mark4;
		this.mark3_5 = mark3_5;
		this.mark3 = mark3;
		this.mark2 = mark2;
		this.testses = testses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SET_ID", unique = true, nullable = false)
	public Integer getSetId() {
		return this.setId;
	}

	public void setSetId(Integer setId) {
		this.setId = setId;
	}

	@Column(name = "MARK_5", nullable = false)
	public int getMark5() {
		return this.mark5;
	}

	public void setMark5(int mark5) {
		this.mark5 = mark5;
	}

	@Column(name = "MARK_4_5", nullable = false)
	public int getMark4_5() {
		return this.mark4_5;
	}

	public void setMark4_5(int mark4_5) {
		this.mark4_5 = mark4_5;
	}

	@Column(name = "MARK_4", nullable = false)
	public int getMark4() {
		return this.mark4;
	}

	public void setMark4(int mark4) {
		this.mark4 = mark4;
	}

	@Column(name = "MARK_3_5", nullable = false)
	public int getMark3_5() {
		return this.mark3_5;
	}

	public void setMark3_5(int mark3_5) {
		this.mark3_5 = mark3_5;
	}

	@Column(name = "MARK_3", nullable = false)
	public int getMark3() {
		return this.mark3;
	}

	public void setMark3(int mark3) {
		this.mark3 = mark3;
	}

	@Column(name = "MARK_2", nullable = false)
	public int getMark2() {
		return this.mark2;
	}

	public void setMark2(int mark2) {
		this.mark2 = mark2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setsOfRating")
	public Set<Test> getTestses() {
		return this.testses;
	}

	public void setTestses(Set<Test> testses) {
		this.testses = testses;
	}

}
