package com.eqms.tests.automated.com.eqms.tests.automated.newtests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddStudentTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private StringBuffer verificationErrors = new StringBuffer();
  @Before
  public void setUp() {

    System.setProperty("webdriver.chrome.driver", "C:/Program Files/chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addStudentTest() throws Exception{
    driver.get("http://localhost:8080/EQMS_war/students/index");
    driver.manage().window().setSize(new Dimension(1382, 744));
    Thread.sleep(1000);
    driver.findElement(By.id("j_username")).clear();
    driver.findElement(By.id("j_username")).sendKeys("andrzej.kowalski@gmail.com");
    Thread.sleep(1000);
    driver.findElement(By.id("j_password")).clear();
    driver.findElement(By.id("j_password")).sendKeys("andrzejkowalski1");
    driver.findElement(By.xpath("//button[@type='submit']")).click();
    driver.findElement(By.linkText("Students")).click();
    Thread.sleep(1000);
    Thread.sleep(1000);
    new Select(driver.findElement(By.id("studentGroupsDropDown"))).selectByVisibleText("grupa3");

    Thread.sleep(1000);
    driver.findElement(By.id("addStudentBtn")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("studentFirstnameModal")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("studentFirstnameModal")).sendKeys("Jan");
    Thread.sleep(1000);
    driver.findElement(By.id("studentLastnameModal")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("studentLastnameModal")).sendKeys("Kowalski");
    Thread.sleep(1000);
    driver.findElement(By.id("studentEmailModal")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("studentEmailModal")).sendKeys("jankowalskimail@mail.pl");
    Thread.sleep(1000);
    driver.findElement(By.id("addStudentBtnModal")).click();
    Thread.sleep(1000);
    try {
      assertEquals("jankowalskimail@mail.pl", driver.findElement(By.cssSelector("td.sorting_1")).getText());
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }
    Thread.sleep(1000);
    driver.findElement(By.id("addStudentBtn")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("studentEmailModal")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("studentEmailModal")).sendKeys("jankowalskimail@mail.pl");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#addStudentModal .modal-content")).click();
    Thread.sleep(1000);
    try {
      assertEquals("This email already exists! Please enter another email name.", driver.findElement(By.id("studentEmailModal-error")).getText());
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }
  }
}
