package com.eqms.tests.automated.com.eqms.tests.automated.newtests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DeleteStudentTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private StringBuffer verificationErrors = new StringBuffer();
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:/Program Files/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteStudentTest() throws Exception{
    driver.get("http://localhost:8080/EQMS_war/auth/login");
    driver.manage().window().setSize(new Dimension(976, 621));
    driver.findElement(By.id("j_username")).clear();
    driver.findElement(By.id("j_username")).sendKeys("andrzej.kowalski@gmail.com");
    Thread.sleep(1000);
    driver.findElement(By.id("j_password")).clear();
    driver.findElement(By.id("j_password")).sendKeys("andrzejkowalski1");
    driver.findElement(By.xpath("//button[@type='submit']")).click();
    driver.findElement(By.linkText("Students")).click();
    Thread.sleep(1000);
    new Select(driver.findElement(By.id("studentGroupsDropDown"))).selectByVisibleText("grupa3");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#students_table_filter .form-control")).click();
    driver.findElement(By.cssSelector("#students_table_filter .form-control")).sendKeys("Jan");
    Thread.sleep(1000);
    driver.findElement(By.id("deleteStudentBtn")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("confirmDeleteStudentBtnModal")).click();
    Thread.sleep(1000);
    try {
      assertEquals("No matching records found", driver.findElement(By.cssSelector("td.dataTables_empty")).getText());
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }
  }
}
