package com.eqms.tests.automated.com.eqms.tests.automated.newtests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExamTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private StringBuffer verificationErrors = new StringBuffer();
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:/Program Files/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void examTest() throws Exception{
    driver.get("http://localhost:8080/EQMS_war/auth/login");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("kamilnowakowski@wp.pl");
    driver.findElement(By.id("j_password")).click();
    driver.findElement(By.id("j_password")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-md")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("startExamBtn")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(2) > #answerReference")).click();
    driver.findElement(By.id("btnNext")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("btnPrevious")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(2) > #answerReference")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(1) > #answerReference")).click();
    driver.findElement(By.id("btnNext")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(2) > #answerReference")).click();
    driver.findElement(By.cssSelector(".container:nth-child(4) > #answerReference")).click();
    driver.findElement(By.id("btnNext")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(1) > #answerReference")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(2) > #answerReference")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(3) > #answerReference")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".container:nth-child(4) > #answerReference")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("btnFinish")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("confirmFinishExamBtnModal")).click();
    Thread.sleep(2000);
    try {
      assertEquals("2", driver.findElement(By.id("score")).getText());
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }
    try {
      assertEquals("3.5", driver.findElement(By.id("mark")).getText());
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }

  }
}
