package com.eqms.tests.automated.com.eqms.tests.automated.newtests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HistoryTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private StringBuffer verificationErrors = new StringBuffer();
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:/Program Files/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void historyTest() throws Exception{
    driver.get("http://localhost:8080/EQMS_war/auth/login");
    driver.manage().window().setSize(new Dimension(976, 621));
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("andrzej.kowalski@gmail.com");
    driver.findElement(By.id("j_password")).click();
    driver.findElement(By.id("j_password")).sendKeys("andrzejkowalski1");
    driver.findElement(By.cssSelector(".btn-md")).click();
    Thread.sleep(1000);
    driver.findElement(By.linkText("History")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#resultsBtn")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("answersBtn")).click();
    Thread.sleep(1000);
    try {
      assertEquals("Selected answer",  driver.findElement(By.cssSelector(".jumbotron:nth-child(2) > #answersloop b")).getText());
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }

  }
}
